### ISSUE TITLE
Any use-examples out there?

### ISSUE THREAD

**Issue by aweussom** [mpromonet/v4l2tools#30]
Can't get screen grab to work on Raspbian:
pi@picam4-b:~/Downloads/v4l2tools $ ./v4l2grab_h264
Open display[0]...
Display is 1920 x 1200
[NOTICE] src/V4l2MmapDevice.cpp:141
VIDIOC_STREAMOFF: Bad file descriptor
VIDIOC_REQBUFS: Bad file descriptor
2019-11-04 19:26:37,815 [WARN  ] - src/v4l2grab_h264.cpp:139
	Cannot create V4L2 output interface for device:

pi@picam4-b:~/Downloads/v4l2tools $ ./v4l2grab_h264 /dev/video13
Open display[0]...
Display is 1920 x 1200
[NOTICE] src/V4l2MmapDevice.cpp:141
VIDIOC_STREAMOFF: Bad file descriptor
VIDIOC_REQBUFS: Bad file descriptor
2019-11-04 19:26:40,833 [WARN  ] - src/v4l2grab_h264.cpp:139
	Cannot create V4L2 output interface for device:/dev/video13

**Comment by mpromonet** [comment]
Hi aweussom,

The purpose of this simple tools is to grab the display, compress into H264 format it, and write it to a V4L2 device.
I always use a [v4l2loopback](https://github.com/umlaeute/v4l2loopback) device as a V4L2 output device in order to feed some consumer like [v4l2rtspserver](https://github.com/mpromonet/v4l2rtspserver).
But maybe it could work with a real output device ?

Best Regards,
Michel.
